#
# File name: .github/workflows/keep_alive.yml
#

name: Render Health Check

on:
  schedule:
    - cron: "*/05 * * * *"
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Run health check
        id: healthcheck
        run: |
          python py/health_check.py
        env:
          RENDER_HEALTH_URL: ${{ secrets.HEALTH_URL }}

      - name: Send email on failure
        if: failure()
        run: |
          python py/send_alert_email.py
        env:
          SENDER_EMAIL: ${{ secrets.GHACTION_POSTMAN }}
          SENDER_EMAIL_PASSWORD: ${{ secrets.GHACTION_MAIL }}
          RECEIVER_EMAIL: ${{ secrets.GHACTION_HOME }}
          RENDER_HEALTH_URL: ${{ secrets.HEALTH_URL }}

#
